parameters: {}
environment: {}
packages:
  - name: gorush-komsoft
    environment: {}
    parameters: {}
    actions:
      - name: gorush
        main: ''
        runtime: 'go:default'
        environment: {}
        parameters: {}
